DATA    SEGMENT
S1  DB  'ABCDEFGHIJKLMNOPQRSTUVW'
    DB  'XYZ0123'
S2  DB  30  DUP(?)
DATA    ENDS

CODE    SEGMENT
    ASSUME  DS: DATA, CS: CODE

START:
    MOV AX, DATA
    MOV DS, AX
    MOV SI, OFFSET S1
    MOV DI, OFFSET S2
    MOV CX, 30
NEXT:
    MOV AL, [SI]
    MOV [DI], AL
    INC SI
    INC DI
    LOOP NEXT
    MOV AH, 4CH
    INT 21H
CODE ENDS
    END START
